"""Check for .gitignore presence."""

from __future__ import annotations

import os
from dataclasses import dataclass, field


@dataclass
class CheckResult:
    status: str  # "ok" | "warn" | "fail"
    message: str
    suggestions: list[str] = field(default_factory=list)


def check(path: str) -> CheckResult:
    gitignore_path = os.path.join(path, ".gitignore")

    if os.path.isfile(gitignore_path):
        return CheckResult(status="ok", message=".gitignore found")

    return CheckResult(
        status="fail",
        message=".gitignore missing",
        suggestions=[
            "Add a .gitignore file to prevent committing build artifacts, secrets, and editor files.",
            "GitHub provides templates at: https://github.com/github/gitignore",
        ],
    )


def fix(path: str) -> None:
    gitignore_path = os.path.join(path, ".gitignore")
    if not os.path.isfile(gitignore_path):
        with open(gitignore_path, "w", encoding="utf-8") as f:
            f.write("# Automatically generated by project-doctor\n")
            f.write("__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.Python\nbuild/\ndevelop-eggs/\ndist/\ndownloads/\neggs/\n.eggs/\nlib/\nlib64/\nparts/\nsdist/\nvar/\nwheels/\nshare/python-wheels/\n*.egg-info/\n.installed.cfg\n*.egg\nMANIFEST\n.env\n.venv\nenv/\nvenv/\nENV/\nenv.bak/\nvenv.bak/\n")
